apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: primary-ingress
spec:
  rules:
  - host: solar.charleshooper.net
    http:
      paths:
      - backend:
          serviceName: solarmon-web
          servicePort: 8080
